In [ ]:
#NUMPY

import numpy as np

print(np.__version__)

1.26.4


In [ ]:
a1=np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1.size)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
5


In [ ]:
#2D ARRAY
a2=np.array([[1,2,3,4],[4,5,6,8]])
print(a2)
print(type(a2))
print(a2.shape)
print(a2.size)
print(a2.ndim)

[[1 2 3 4]
 [4 5 6 8]]
<class 'numpy.ndarray'>
(2, 4)
8
2


In [ ]:
#3D ARRAY
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
print(type(a3))
print(a3.shape)
print(a3.ndim)
print(a3.size)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
(1, 3, 3)
3
9


In [ ]:

z1=np.zeros((3))
print(z1)


[0. 0. 0.]


In [ ]:
#CHANGING DATA TYPE

z1=np.zeros((3),dtype=np.int64)
print(z1)
print(type(z1))
print(z1.shape)
print(z1.size)
print(z1.ndim)
print(z1.dtype)

[0 0 0]
<class 'numpy.ndarray'>
(3,)
3
1
int64


In [ ]:
z2=np.zeros((3,4),dtype=np.int64)
print(z2)
print(type(z2))
print(z2.shape)
print(z2.size)
print(z2.ndim)
print(z2.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
<class 'numpy.ndarray'>
(3, 4)
12
2
int64


In [ ]:
z3=np.zeros((2,3,4),dtype=np.int64)
print(z3)
print(type(z3))
print(z3.shape)
print(z3.size)
print(z3.ndim)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.ndarray'>
(2, 3, 4)
24
3


In [ ]:
#ID ONES ARRAY
import numpy as np
o1=np.ones((3))
print(o1)

[1. 1. 1.]


In [ ]:
a1=np.ones((3,4))
print(a1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#2D ONES ARRAY

a2=np.ones((3,4),dtype=np.int64)
print(a2)
print(a2.shape)
print(a2.size)
print(a2.ndim)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(3, 4)
12
2


In [ ]:
#3D ONES ARRAY
a3=np.ones([4,2,3],dtype=int)
print(a3)
print(type(a3))
print(a3.shape)
print(a3.size)
print(a3.ndim)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
(4, 2, 3)
24
3


In [ ]:
#1D FULL ARRAY

f1=np.full(3,9,dtype=int)
print(f1)
print(type(f1))
print(f1.shape)
print(f1.size)
print(f1.ndim)

[9 9 9]
<class 'numpy.ndarray'>
(3,)
3
1


In [ ]:
#2D FULL ARRAY

f2=np.full((2,3),9,dtype=int)
print(f2)
print(type(f2))
print(f2.shape)
print(f2.size)
print(f2.ndim)

[[9 9 9]
 [9 9 9]]
<class 'numpy.ndarray'>
(2, 3)
6
2


In [ ]:
#3D FULL ARRAY

f3=np.full((2,3,4),9,dtype=int)
print(f3)
print(type(f3))
print(f3.shape)
print(f3.size)
print(f3.ndim)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]
<class 'numpy.ndarray'>
(2, 3, 4)
24
3


In [ ]:
#ADD

a=np.array([1,2,3])
b=np.array([1,2,3])

add=np.add(a,b)
add

array([2, 4, 6])

In [ ]:
#SUBTRACT
a=np.array([5,10,20])
b=np.array([4,8,10])

sub=np.subtract(a,b)
sub

array([ 1,  2, 10])

In [ ]:
#MULTIPLY
a=np.array([5,10,20])
b=np.array([4,8,10])

mul=np.multiply(a,b)
mul


array([ 20,  80, 200])

In [ ]:
#DIVIDE
a=np.array([5,10,20])
b=np.array([4,8,10])

div=np.divide(a,b)
div

array([1.25, 1.25, 2.  ])

In [ ]:
#MOD
a=np.array([5,10,20])
b=np.array([4,8,10])

mod=np.mod(a,b)
mod

array([1, 2, 0])

In [ ]:
#POWER
a=np.array([5,10,20])
b=np.array([4,8,10])

pow=np.power(a,b)
pow

array([           625,      100000000, 10240000000000])